Add controllers
iliodor1/java-shareit pull request #2
Opened 2022-07-26 12:41 UTC by iliodor1

2022-07-27 10:25 UTC, FanaticFiz requested changes
Основной комментарий оставлю на практикуме.

2022-07-27 10:25 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                              @RequestBody ItemDto itemDto) {
Валидация нужна и при обновлении!

2022-07-27 10:25 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public ItemDto getItem(Long userId, Long id) {
А у меня вот такие настройки стилизации:

```
@Override
public ItemDto getItem(Long userId, Long id) {
    Item item = itemRepository.getItem(id)
                              .orElseThrow(() -> {
                                  log.error("Item with id {} not found", id);
                                  return new NotFoundException("Item not found with id: " + id);
                              });

    return itemMapper.toDto(item);
}
```

Ну т.е. все операции через `.` выравниваются.

2022-07-27 10:25 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    Item addItem(Long ownerId, Item item);
Мы не добавляем, а создаём! Уместнее будет переназвать.

2022-07-27 10:25 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (text.isBlank()) return List.of();
В `Java` не принято экономить на `{}`

2022-07-27 10:25 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto updateUser(@PathVariable Long id, @RequestBody UserDto userDto) {
Пропущена валидация...

2022-07-27 10:25 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemory.java
> +        if (isUniqueEmail(user)) {
Тебе будет полезно узнать про метод `computeIfAbsent` из `Map`

2022-08-02 04:22 UTC, iliodor1 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +
Привет. Я так понимаю, их не нужно реализовывать в этом спринте. В техзадание указано, что "Создание DTO-объектов и мапперов
Созданные объекты Item и User вы в дальнейшем будете использовать для работы с базой данных (это ждёт вас в следующем спринте)...
Разработка контроллеров
... Для начала научите ваше приложение работать с пользователями...
...Далее переходите к основной функциональности этого спринта — работе с вещами..."

И тесты написаны только для Item и User

2022-08-02 04:22 UTC, iliodor1 commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemory.java
> +        if (isUniqueEmail(user)) {
Если честно, я не совсем понял, как можно реализовать этот метод в этом условии. computeIfAbsent принимает ключ и в случае отсутствия/null этого ключа вычисляет новое значение для этого ключа. Поправь, если я ошибаюсь

2022-08-02 06:38 UTC, FanaticFiz approved these changes
Финальный коммент, как обычно, на Я.Практикуме )

2022-08-02 06:38 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryInMemory.java
> +        if (!isContainsUser(ownerId)) {
По поводу всего этого условия.
Ты всегда используешь этот метод с отрицанием `!`, а значит уместнее будет инвертировать логику.
А если еще и переименовать метод, то получится куда более читаемое условие:
`if (!isContainsUser(ownerId)) -> if (userNotExist(ownerId))`

2022-08-02 06:38 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryInMemory.java
>          if (!item.getAvailable()) {
И тут же можно увидеть недостатки Lombok, видишь с каким названием он сгенерировал для boolean параметра метод get -> `getAvailable`.
Но для булева принято не называть метод `get`, а именовать его: `isAvailable`

Тебе не нужно ничего исправлять, просто прими к сведению, ну и найди статьи о том как не стоит применять ломбок.

2022-08-02 06:38 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    Long ownerId;
Ты по-прежнему используешь `id` вместо самой сущности пользователя!
Как тут так и в сущности `ItemRequest`

Должно быть: `User owner; User requester;`

2022-08-02 06:38 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/UserRepositoryInMemory.java
> +        if (isUniqueEmail(user)) {
Да, тут стоит провести дополнительные действия для того чтобы избежать вот такого перебора в лоб.
В предыдущих задачах мы несколько раз применяли один и тот же приём... попробуй вспомнить и за использовать, но это не обязательно, ты не заметишь деградацию на маленьком кол-ве пользователей...

2022-08-08 05:38 UTC, merged